{% set name = "ogstools" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ogstools-{{ version }}.tar.gz
  sha256: a65fa36a107b14c01ac274c7f52416dc89f80cd88abb7f26af54850b876da01f

build:
  entry_points:
    - msh2vtu = ogstools.msh2vtu._cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.9
      # TODO: create conda-forge packages:
      #- ogs
      #- ogs6py
      #- vtuinterface
    - meshio ==5.3.4
    - jupytext
    - matplotlib
    - nbconvert
    - pandas
    - papermill
    - pillow
    - pint
    - pyvista
    - scipy
    - tqdm
    - typeguard

test:
  imports:
    - ogstools
  commands:
    #- pip check
    - msh2vtu --help
    - pytest
  requires:
    - pip
    - pytest
  source_files:
    - tests

about:
  home: https://pypi.org/project/ogstools/
  summary: A collection of Python tools aimed at evolving into a modeling toolchain around OpenGeoSys.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bilke
