{% set python_min = "3.10" %}
{% set name = "ogstools" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ogstools-{{ version }}.tar.gz
  sha256: 593d2ed22d254419abe7e806782379f84b12a7dfc3425ec8939add12e603d120

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - python-gmsh >=4.12.0
    - h5py >=3.8.0
    - jupytext >=1.14.0
    - matplotlib-base >=3.7.1
    - meshio >=5.3.0
    - pyvista >=0.40.1
    - numpy >=1.20.0,<2.1
    - scipy >=1.10.1
    - pint >=0.22
    - papermill >=2.4.0
    - pandamesh >=0.2.1
    - typeguard >=4.0.0
    - lxml >=4.6.0
    - ogs >=6.5.4
    - pandas >=2.2.3
    - psutil >=6.0.0
    - simpleeval >=1.0.3

test:
  requires:
    - python {{ python_min }}
  imports:
    - ogstools
  commands:
    # - pip check # does not work because of gmsh and ogs package
    - msh2vtu --help
    # - feflow2ogs --help
  # requires:
  #  - pip

about:
  home: https://pypi.org/project/ogstools/
  summary: A collection of Python tools aimed at evolving into a modeling toolchain around OpenGeoSys.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bilke
