{% set name = "ogstools" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ogstools-{{ version }}.tar.gz
  sha256: 935040fee60b41351395577e3560f62edcf1fd8fbf9cb06d0776293fe5cb2b42

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.10
    - python-gmsh >=4.12.0
    - h5py >=3.8.0
    - jupytext >=1.14.0
    - matplotlib-base >=3.7.1
    - meshio >=5.3.0
    - pyvista >=0.40.1
    - numpy >=1.20.0,<2.1
    - scipy >=1.10.1
    - pint >=0.22
    - papermill >=2.4.0
    - pandamesh >=0.2.1
    - typeguard >=4.0.0
    - lxml >=4.6.0
    - ogs >=6.5.4
    - pandas >=2.2.3

test:
  imports:
    - ogstools
  commands:
    # - pip check # does not work because of gmsh and ogs package
    - msh2vtu --help
    - shp2msh --help
    # - feflow2ogs --help
  # requires:
  #  - pip

about:
  home: https://pypi.org/project/ogstools/
  summary: A collection of Python tools aimed at evolving into a modeling toolchain around OpenGeoSys.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bilke
