{% set name = "ogstools" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ogstools-{{ version }}.tar.gz
  sha256: 8502fda985f789243787afbf4e75db6eda7aa04a94b806c1ecd1f8430d1c9043

build:
  entry_points:
    - msh2vtu = ogstools.msh2vtu._cli:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - meshio >=5.3.0

test:
  imports:
    - ogstools
  commands:
    - pip check
    - msh2vtu --help
  requires:
    - pip

about:
  home: https://pypi.org/project/ogstools/
  summary: A collection of Python tools aimed at evolving into a modeling toolchain around OpenGeoSys.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bilke
